### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by titivermeesch** [titivermeesch/CommandTimer#112]
```
[16:07:53] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CommandTimer v6.1
java.lang.ExceptionInInitializerError: null
	at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[commandtimer-6.1.jar:?]
	at me.playbosswar.com.gui.tasks.EditTaskMenu.lambda$init$0(EditTaskMenu.java:41) ~[commandtimer-6.1.jar:?]
	at fr.minuskube.inv.ClickableItem.run(ClickableItem.java:26) ~[commandtimer-6.1.jar:?]
	at fr.minuskube.inv.InventoryManager$InvListener.lambda$onInventoryClick$2(InventoryManager.java:140) ~[commandtimer-6.1.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at fr.minuskube.inv.InventoryManager$InvListener.onInventoryClick(InventoryManager.java:140) ~[commandtimer-6.1.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1442]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2901) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1437) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1415) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1408) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1542) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: AnvilGUI does not support server version "1_18_R1"
	at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:26) ~[commandtimer-6.1.jar:?]
	at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[commandtimer-6.1.jar:?]
	... 27 more
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.version.Wrapper1_18_R1
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:22) ~[commandtimer-6.1.jar:?]
	at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[commandtimer-6.1.jar:?]
	... 27 more
[16:07:54] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CommandTimer v6.1
java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
	at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[commandtimer-6.1.jar:?]
	at me.playbosswar.com.gui.tasks.EditTaskMenu.lambda$init$0(EditTaskMenu.java:41) ~[commandtimer-6.1.jar:?]
	at fr.minuskube.inv.ClickableItem.run(ClickableItem.java:26) ~[commandtimer-6.1.jar:?]
	at fr.minuskube.inv.InventoryManager$InvListener.lambda$onInventoryClick$2(InventoryManager.java:140) ~[commandtimer-6.1.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at fr.minuskube.inv.InventoryManager$InvListener.onInventoryClick(InventoryManager.java:140) ~[commandtimer-6.1.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1442]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2901) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1437) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1415) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1408) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1386) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1292) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1442]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by titivermeesch** [comment]
Covered in v6.1.1
