### ISSUE TITLE
GUI elements not working

### ISSUE THREAD

**Issue by jaroslawjanas** [titivermeesch/CommandTimer#128]
Elements not working:

- Task Name
- Change Command

Environment:
- Paper version git-Paper-259 (MC: 1.18.2)
-  Plugins: ` ChestSort, CleanroomGenerator, CommandTimer, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, Minepacks, Multiverse-Core, Randomtp, ServerRestorer, ServerTutorialPlus*, Vault, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags`

Error:
```
[00:19:44 ERROR]: Could not pass event InventoryClickEvent to CommandTimer v6.2
java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[commandtimer-6.2-all.jar:?]
        at me.playbosswar.com.gui.tasks.EditTaskMenu.lambda$init$0(EditTaskMenu.java:41) ~[commandtimer-6.2-all.jar:?]
        at fr.minuskube.inv.ClickableItem.run(ClickableItem.java:26) ~[commandtimer-6.2-all.jar:?]
        at fr.minuskube.inv.InventoryManager$InvListener.lambda$onInventoryClick$2(InventoryManager.java:140) ~[commandtimer-6.2-all.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at fr.minuskube.inv.InventoryManager$InvListener.onInventoryClick(InventoryManager.java:140) ~[commandtimer-6.2-all.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-259]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2860) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-259]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:20:53 ERROR]: Could not pass event InventoryClickEvent to CommandTimer v6.2
java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[commandtimer-6.2-all.jar:?]
        at me.playbosswar.com.gui.api.GenericTextMenu.<init>(GenericTextMenu.java:26) ~[commandtimer-6.2-all.jar:?]
        at me.playbosswar.com.gui.tasks.commands.EditCommandNameMenu.<init>(EditCommandNameMenu.java:9) ~[commandtimer-6.2-all.jar:?]
        at me.playbosswar.com.gui.tasks.commands.EditCommandMenu.lambda$init$0(EditCommandMenu.java:39) ~[commandtimer-6.2-all.jar:?]
        at fr.minuskube.inv.ClickableItem.run(ClickableItem.java:26) ~[commandtimer-6.2-all.jar:?]
        at fr.minuskube.inv.InventoryManager$InvListener.lambda$onInventoryClick$2(InventoryManager.java:140) ~[commandtimer-6.2-all.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at fr.minuskube.inv.InventoryManager$InvListener.onInventoryClick(InventoryManager.java:140) ~[commandtimer-6.2-all.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-259]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2860) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-259]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by titivermeesch** [comment]
Thanks for your report. There are indeed issues with 1.18.2, related to AnvilGUI. A fix is coming for it

**Comment by titivermeesch** [comment]
Issue has been fixed
