### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by Drc-DEV** [titivermeesch/CommandTimer#13]
```
[15:29:19] [Server thread/INFO]: [CommandTimer] Enabling CommandTimer v2.2*
[15:29:19] [Server thread/ERROR]: Error occurred while enabling CommandTimer v2.2 (Is it up to date?)
java.lang.NullPointerException: null
	at me.playbosswar.com.Tools.getGender(Tools.java:62) ~[?:?]
	at me.playbosswar.com.TaskRunner.startTasks(TaskRunner.java:20) ~[?:?]
	at me.playbosswar.com.CommandTimer.onEnable(CommandTimer.java:23) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-507]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-507]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-507]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-507]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-507]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-507]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-507]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-507]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-507]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-507]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
```

PaperSpigot 1.13.2

**Comment by titivermeesch** [comment]
Did you specify the gender in the config file correctly?

**Comment by Drc-DEV** [comment]
What do you mean? gender what?

**Comment by titivermeesch** [comment]
gender: 'console'

Or player or operator. It says that you don't have specified that correctly

**Comment by Drc-DEV** [comment]
Thanks. I updated from a really old version and I did not reset the config. Now it's working fine.
