### ISSUE TITLE
1.19.1 condition issue

### ISSUE THREAD

**Issue by titivermeesch** [titivermeesch/CommandTimer#149]
When I activate a timer with paper 1.19.1 in the console this error is spammed:

[15:18:44 WARN]: [CommandTimer] Task #99846 for CommandTimer v6.2.4 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
        at me.playbosswar.cmtplayerconditions.utils.WorldTimeTracking.getSecondsInWorldForPlayer(WorldTimeTracking.java:57) ~[?:?]
        at me.playbosswar.cmtplayerconditions.conditions.PlayerTimeInWorldCondition.evaluate(PlayerTimeInWorldCondition.java:41) ~[?:?]
        at me.playbosswar.com.tasks.TaskValidationHelpers.checkSimpleCondition(TaskValidationHelpers.java:99) ~[commandtimer-java17.jar:?]
        at me.playbosswar.com.tasks.TaskValidationHelpers.lambda$processCondition$0(TaskValidationHelpers.java:33) ~[commandtimer-java17.jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?]
        at me.playbosswar.com.tasks.TaskValidationHelpers.processCondition(TaskValidationHelpers.java:31) ~[commandtimer-java17.jar:?]
        at me.playbosswar.com.tasks.TasksManager.runPlayerCommand(TasksManager.java:105) ~[commandtimer-java17.jar:?]
        at me.playbosswar.com.tasks.TasksManager$1.lambda$run$0(TasksManager.java:169) ~[commandtimer-java17.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at me.playbosswar.com.tasks.TasksManager$1.run(TasksManager.java:162) ~[commandtimer-java17.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-94]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.1.jar:git-Paper-94]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1491) ~[paper-1.19.1.jar:git-Paper-94]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.1.jar:git-Paper-94]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.1.jar:git-Paper-94]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-94]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-94]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by titivermeesch** [comment]
Will be included in v6.3
