### ISSUE TITLE
Possible plugin incompatibility (InteractiveChat)

### ISSUE THREAD

**Issue by MCHalfAssed** [titivermeesch/CommandTimer#177]
When I install this plugin: (InteractiveChat: https://www.spigotmc.org/resources/interactivechat-show-items-inventory-in-chat-custom-chat-keywords-bungee-velocity-support.75870/) , I'm not able to send input into the chat when CMT asks for it. It says "Enter your new task name", I type it in, and I just send a message to chat instead of going back into CMT.  (I uninstalled InteractiveChat and CMT worked normally again).

 It looks like InteractiveChat is overriding something important for CMT, but after going in the config, I'm not sure what it is or what to change. I was hoping you could give some input?
 
 Also, here's the config for InteractiveChat 🙂
[InteractiveChat_config.txt](https://github.com/titivermeesch/CommandTimer/files/10329384/InteractiveChat_config.txt)

**Comment by titivermeesch** [comment]
Duplicate of existing ticket #176, but closing that one because this has more information

**Comment by MCHalfAssed** [comment]
Not sure if this is related, but I got this error today (It could have been related to be adding a command by only creating a YML myself and not using the GUI, lol):

`[03:19:11] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CommandTimer v7.1.1
java.lang.ClassCastException: class java.lang.String cannot be cast to class me.playbosswar.com.conditionsengine.ConditionCompare (java.lang.String is in module java.base of loader 'bootstrap'; me.playbosswar.com.conditionsengine.ConditionCompare is in unnamed module of loader 'commandtimer-java17.jar' @72b3765c)
	at me.playbosswar.com.gui.conditions.inputs.ConditionCompareItem.get(ConditionCompareItem.java:39) ~[commandtimer-java17.jar:?]
	at me.playbosswar.com.gui.conditions.ConditionMenu.init(ConditionMenu.java:129) ~[commandtimer-java17.jar:?]
	at fr.minuskube.inv.SmartInventory.open(SmartInventory.java:52) ~[commandtimer-java17.jar:?]
	at fr.minuskube.inv.SmartInventory.open(SmartInventory.java:35) ~[commandtimer-java17.jar:?]
	at me.playbosswar.com.gui.tasks.EditTaskMenu.lambda$init$6(EditTaskMenu.java:89) ~[commandtimer-java17.jar:?]
	at fr.minuskube.inv.ClickableItem.run(ClickableItem.java:26) ~[commandtimer-java17.jar:?]
	at fr.minuskube.inv.InventoryManager$InvListener.lambda$onInventoryClick$2(InventoryManager.java:140) ~[commandtimer-java17.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at fr.minuskube.inv.InventoryManager$InvListener.onInventoryClick(InventoryManager.java:140) ~[commandtimer-java17.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-368]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3159) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-368]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]`

**Comment by MCHalfAssed** [comment]
This issue was fixed here!
https://github.com/LOOHP/InteractiveChat/issues/131
