### ISSUE TITLE
Waterfall

### ISSUE THREAD

**Issue by Y3ko** [titivermeesch/CommandTimer#23]
[15:11:05] [main/WARN]: Error enabling plugin CommandTimer
java.lang.NoClassDefFoundError: org/bukkit/event/Listener
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_222]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_222]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_222]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_222]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_222]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_222]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_222]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_222]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:03a06e4:293]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:03a06e4:293]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:360) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:03a06e4:293]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:268) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:03a06e4:293]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:269) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:03a06e4:293]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:03a06e4:293]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:03a06e4:293]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.Listener
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:03a06e4:293]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:03a06e4:293]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
	... 18 more

**Comment by titivermeesch** [comment]
Hi, can you please show your config

**Comment by titivermeesch** [comment]
It also seems like you are using Waterfall, is that an alternative to Bungee?

**Comment by Y3ko** [comment]
I can't show you config because it is no config. And plugin is not opening.

Yes alternative for bunngee

**Comment by titivermeesch** [comment]
The plug-in is not made to be installed on bungeecord, it is a spigot only plug-in but has a bungee extension that isn't published yet
