### ISSUE TITLE
ExpansionRegisterEvent may only be triggered synchronously.

### ISSUE THREAD

**Issue by Erorserv** [titivermeesch/CommandTimer#60]
When the set time is reached, the command will not execute but instead show the following in console.

Config:
```
#GENERAL
timeonload: true

tasks:
  command_time:
    commands:
      - say This message will only show up at a specific time.
    time:
      - "17:13:00" # Use HH:mm:ss for real life time and HH:mm for minecraft time (useMinecraftTime: true)
    gender: console
```

Console:
```
[Thu, 11. Jun 2020 17:13:00 AEST WARN] Exception in thread "Timer-2" java.lang.IllegalStateException: ExpansionRegisterEvent may only be triggered synchronously.
[Thu, 11. Jun 2020 17:13:00 AEST WARN]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595)
[Thu, 11. Jun 2020 17:13:00 AEST WARN]     at me.clip.placeholderapi.PlaceholderAPI.registerExpansion(PlaceholderAPI.java:460)
[Thu, 11. Jun 2020 17:13:00 AEST WARN]     at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:122)
[Thu, 11. Jun 2020 17:13:00 AEST WARN]     at me.playbosswar.com.hooks.PAPIHook.parsePAPI(PAPIHook.java:14)
[Thu, 11. Jun 2020 17:13:00 AEST WARN]     at me.playbosswar.com.Tools.executeCommand(Tools.java:246)
[Thu, 11. Jun 2020 17:13:00 AEST WARN]     at me.playbosswar.com.Tools$2.run(Tools.java:197)
[Thu, 11. Jun 2020 17:13:00 AEST WARN]     at java.util.TimerThread.mainLoop(Timer.java:555)
[Thu, 11. Jun 2020 17:13:00 AEST WARN]     at java.util.TimerThread.run(Timer.java:505)
```

Running Tuinity version git-Tuinity-"121cca1" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by titivermeesch** [comment]
This is because you are not running on Vanilla Spigot. Forks of Spigot will be supported in v5
