### ISSUE TITLE
I used Vanila spigot , but have bug: ExpansionRegisterEvent may only be trigg ered synchronously.

### ISSUE THREAD

**Issue by AnateXP** [titivermeesch/CommandTimer#61]
Exception in thread "Timer-4" java.lang.IllegalStateException: ExpansionRegisterEvent may only be trigg
ered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533)
        at me.clip.placeholderapi.PlaceholderAPI.registerExpansion(PlaceholderAPI.java:460)
        at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:122)

        at me.playbosswar.com.hooks.PAPIHook.parsePAPI(PAPIHook.java:14)
        at me.playbosswar.com.Tools.executeCommand(Tools.java:246)
        at me.playbosswar.com.Tools$2.run(Tools.java:197)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)
 Exception in thread "Timer-2" java.lang.IllegalStateException: ExpansionRegisterEvent may only be trigg
ered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533)
        at me.clip.placeholderapi.PlaceholderAPI.registerExpansion(PlaceholderAPI.java:460)
        at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:122)

        at me.playbosswar.com.hooks.PAPIHook.parsePAPI(PAPIHook.java:14)
        at me.playbosswar.com.Tools.executeCommand(Tools.java:246)
        at me.playbosswar.com.Tools$2.run(Tools.java:197)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)

Config:
#GENERAL
timeonload: true
command_alias: ct

tasks:
 command_time:
   commands:
     - say This message will only show up at a specific time.
   time:
     - "00:59:00" # Use HH:mm:ss for real life time and HH:mm for minecraft time (useMinecraftTime: true)
   gender: console

How to fix it , i looked old issue to say this , but i use vanila spigot , have bug

**Comment by titivermeesch** [comment]
Are you sure that you are using Vanilla Spigot? This looks like an obvious PaperSpigot issue

**Comment by titivermeesch** [comment]
Which version are you on?

**Comment by AnateXP** [comment]
spigot-1.14.4.jar use BuildTools.jar to build , first i used paperspigot but it bug , i change to vanila spigot and also have bug 
OS : Windows 8.1

[08:04:29] [Server thread/INFO]: This server is running CraftBukkit version git-
Spigot-cbd1a1b-009d8af (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSH
OT)
[08:04:29] [Server thread/INFO]: This is a final build for 1.14.4. Please see ht
tps://www.spigotmc.org/go/1.14.4 for details about upgrading.
[08:05:00] [Timer-3/WARN]: Exception in thread "Timer-3"
[08:05:00] [Timer-3/WARN]: java.lang.IllegalStateException: ExpansionRegisterEve
nt cannot be triggered asynchronously from another thread.
[08:05:00] [Timer-3/WARN]:      at org.bukkit.plugin.SimplePluginManager.callEve
nt(SimplePluginManager.java:511)
[08:05:00] [Timer-3/WARN]:      at me.clip.placeholderapi.PlaceholderAPI.registe
rExpansion(PlaceholderAPI.java:460)
[08:05:00] [Timer-3/WARN]:      at me.clip.placeholderapi.expansion.PlaceholderE
xpansion.register(PlaceholderExpansion.java:122)
[08:05:00] [Timer-3/WARN]:      at me.playbosswar.com.hooks.PAPIHook.parsePAPI(P
APIHook.java:14)
[08:05:00] [Timer-3/WARN]:      at me.playbosswar.com.Tools.executeCommand(Tools
.java:246)
[08:05:00] [Timer-3/WARN]:      at me.playbosswar.com.Tools$2.run(Tools.java:197
)
[08:05:00] [Timer-3/WARN]:      at java.util.TimerThread.mainLoop(Unknown Source
)
[08:05:00] [Timer-3/WARN]:      at java.util.TimerThread.run(Unknown Source)

**Comment by AnateXP** [comment]
I use papi have bug , not use papi have bug , i really don't know how to fix it and i want to fix it , because i think this is a very good plugin , i need it , please

**Comment by Skytoone** [comment]
Hello, same problem for me...

**Comment by Skytoone** [comment]
> [02:22:00] [Timer-13/WARN]: Exception in thread "Timer-13"
> [02:22:00] [Timer-15/WARN]: Exception in thread "Timer-15"
> [02:22:00] [Timer-14/WARN]: Exception in thread "Timer-14"
> [02:22:00] [Timer-12/WARN]: Exception in thread "Timer-12"
> [02:22:00] [Timer-14/WARN]: java.lang.IllegalStateException: ExpansionRegisterEvent cannot be triggered asynchronously from another thread.
> [02:22:00] [Timer-14/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
> [02:22:00] [Timer-14/WARN]: at me.clip.placeholderapi.PlaceholderAPI.registerExpansion(PlaceholderAPI.java:460)
> [02:22:00] [Timer-14/WARN]: at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:122)
> [02:22:00] [Timer-14/WARN]: at me.playbosswar.com.hooks.PAPIHook.parsePAPI(PAPIHook.java:14)
> [02:22:00] [Timer-14/WARN]: at me.playbosswar.com.Tools.executeCommand(Tools.java:246)
> [02:22:00] [Timer-14/WARN]: at me.playbosswar.com.Tools$2.run(Tools.java:197)
> [02:22:00] [Timer-14/WARN]: at java.util.TimerThread.mainLoop(Timer.java:555)
> [02:22:00] [Timer-14/WARN]: at java.util.TimerThread.run(Timer.java:505)
> [02:22:00] [Timer-15/WARN]: java.lang.IllegalStateException: ExpansionRegisterEvent cannot be triggered asynchronously from another thread.
> [02:22:00] [Timer-15/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
> [02:22:00] [Timer-15/WARN]: at me.clip.placeholderapi.PlaceholderAPI.registerExpansion(PlaceholderAPI.java:460)
> [02:22:00] [Timer-15/WARN]: at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:122)
> [02:22:00] [Timer-15/WARN]: at me.playbosswar.com.hooks.PAPIHook.parsePAPI(PAPIHook.java:14)
> [02:22:00] [Timer-15/WARN]: at me.playbosswar.com.Tools.executeCommand(Tools.java:246)
> [02:22:00] [Timer-15/WARN]: at me.playbosswar.com.Tools$2.run(Tools.java:197)
> [02:22:00] [Timer-15/WARN]: at java.util.TimerThread.mainLoop(Timer.java:555)
> [02:22:00] [Timer-15/WARN]: at java.util.TimerThread.run(Timer.java:505)
> [02:22:00] [Timer-13/WARN]: java.lang.IllegalStateException: ExpansionRegisterEvent cannot be triggered asynchronously from another thread.
> [02:22:00] [Timer-13/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
> [02:22:00] [Timer-13/WARN]: at me.clip.placeholderapi.PlaceholderAPI.registerExpansion(PlaceholderAPI.java:460)
> [02:22:00] [Timer-13/WARN]: at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:122)
> [02:22:00] [Timer-13/WARN]: at me.playbosswar.com.hooks.PAPIHook.parsePAPI(PAPIHook.java:14)
> [02:22:00] [Timer-13/WARN]: at me.playbosswar.com.Tools.executeCommand(Tools.java:246)
> [02:22:00] [Timer-13/WARN]: at me.playbosswar.com.Tools$2.run(Tools.java:197)
> [02:22:00] [Timer-13/WARN]: at java.util.TimerThread.mainLoop(Timer.java:555)
> [02:22:00] [Timer-13/WARN]: at java.util.TimerThread.run(Timer.java:505)
> [02:22:00] [Timer-12/WARN]: java.lang.IllegalStateException: ExpansionRegisterEvent cannot be triggered asynchronously from another thread.
> [02:22:00] [Timer-12/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
> [02:22:00] [Timer-12/WARN]: at me.clip.placeholderapi.PlaceholderAPI.registerExpansion(PlaceholderAPI.java:460)
> [02:22:00] [Timer-12/WARN]: at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:122)
> [02:22:00] [Timer-12/WARN]: at me.playbosswar.com.hooks.PAPIHook.parsePAPI(PAPIHook.java:14)
> [02:22:00] [Timer-12/WARN]: at me.playbosswar.com.Tools.executeCommand(Tools.java:246)
> [02:22:00] [Timer-12/WARN]: at me.playbosswar.com.Tools$2.run(Tools.java:197)
> [02:22:00] [Timer-12/WARN]: at java.util.TimerThread.mainLoop(Timer.java:555)
> [02:22:00] [Timer-12/WARN]: at java.util.TimerThread.run(Timer.java:505)

**Comment by AnateXP** [comment]
WTF i use CommandTimer old version v4.2 not have this bug but v4.3.1 have bug and can't work , @titivermeesch

**Comment by titivermeesch** [comment]
That's because you use PaperSpigot

**Comment by titivermeesch** [comment]
Or something else. Those issues will be fixed on v5
