### ISSUE TITLE
IllegalStateException: Asynchronous command dispatch!

### ISSUE THREAD

**Issue by johnyuki** [titivermeesch/CommandTimer#63]
When having tasks run at a specific time of day, I get the following error when the task tries to run:

```
[20:34:00] [Timer-9/WARN]: Exception in thread "Timer-9"
[20:34:00] [Timer-9/WARN]: java.lang.IllegalStateException: Asynchronous command dispatch!
[20:34:00] [Timer-9/WARN]:      at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[20:34:00] [Timer-9/WARN]:      at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:754)
[20:34:00] [Timer-9/WARN]:      at me.playbosswar.com.Tools.executeCommand(Tools.java:246)
[20:34:00] [Timer-9/WARN]:      at me.playbosswar.com.Tools$2.run(Tools.java:197)
[20:34:00] [Timer-9/WARN]:      at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[20:34:00] [Timer-9/WARN]:      at java.base/java.util.TimerThread.run(Timer.java:506)
```

This is the task I'm using: 
```
tasks:
  command_time:
    commands:
      - say This message will only show up at a specific time.
    time:
      - "20:34:00" # Use HH:mm:ss for real life time and HH:mm for minecraft time (useMinecraftTime: true)
    gender: console
```

I am using 1.16 though, which I know is not listed on the tested versions.

**Comment by titivermeesch** [comment]
PaperSpigot is not supported in the latest version. Please downgrade to v4.2
