### ISSUE TITLE
1.17.1 support

### ISSUE THREAD

**Issue by wtlgo** [titivermeesch/CommandTimer#94]
The plugin doesn't really work on 1.17.1 sadly.

```
[13:10:51 INFO]: MikChan issued server command: /cmt create test
[13:10:55 INFO]: MikChan issued server command: /cmt info test
org.bukkit.command.CommandException: Unhandled exception executing command 'cmt' in plugin CommandTimer v5.2
[13:10:55 ERROR]: null
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-130]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-130]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:830) ~[patched_1.17.1.jar:git-Paper-130]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-130]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.util.thread.BlockableEventLoop.doRunTasklockableEventLoop.java:149) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-130]
at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-130]
at net.minecraft.util.thread.BlockableEventLoop.pollTasklockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-130]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-130]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-130]
at net.minecraft.util.thread.BlockableEventLoop.managedBlocklockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-130]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-130]
Caused by: java.lang.NullPointerException: Cannot invoke "me.playbosswar.com.chat.api.protocol.ChatPacketInterceptor.getChat(org.bukkit.entity.Player)" because "me.playbosswar.com.chat.api.menu.ChatMenuAPI.interceptor" is null
at java.lang.Thread.run(Thread.java:831) [?:?]
at me.playbosswar.com.chat.api.menu.ChatMenuAPI.getChatIntercept(ChatMenuAPI.java:85) ~[?:?]
at me.playbosswar.com.chat.api.menu.ChatMenu.openFor(ChatMenu.java:161) ~[?:?]
at me.playbosswar.com.chat.ChatMenus.openTimerMenu(ChatMenus.java:141) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-130]
at me.playbosswar.com.commands.MainCommand.onCommand(MainCommand.java:71) ~[?:?]
... 21 more
```

Running on PaperMC 1.17.1 #130

**Comment by titivermeesch** [comment]
@wtlgo Thanks for your report. This issue will be fixed in v6 but it's not yet released. You can probably just edit the files without passing through the /cmt info command
